# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [4]:
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

if(numbers_x[0]==numbers_x[-1]):
  result_x=True
else:
  result_x=False
print(f"Result of numbers_x:",result_x)
if(numbers_y[0]==numbers_y[-1]):
  result_y=True
else:
  result_y=False
  print(f"Result of numbers_y:",result_y)


Result of numbers_x: True
Result of numbers_y: False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [28]:
#Create two NumPy arrays of the same shape and perform element-wise addition on them.
import numpy as np
arr = np.array([[1, 2, 3], [4,5,6], [7,8,9]])
sum=0
for i in (range(len(arr))):
  for j in (range(len(arr[i]))):
    sum+=arr[i][j]
print("Sum:",sum)

#Calculate the element-wise product of two NumPy arrays.
product=np.zeros((3,3))
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in (range(len(arr1))):
  for j in (range(len(arr1[i]))):
    product[i][j]=arr1[i][j]*arr2[i][j]
print(product)


Sum: 45
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [47]:
#Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).
import numpy as np
Array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(Array.reshape(3,4))

#Concatenate two NumPy arrays horizontally and vertically.
Array1=np.array([[1,2,3],[4,5,6]])
Array2=np.array([[7,8,9],[10,11,12]])
horizontal=np.concatenate((Array1,Array2),axis=0)
print(horizontal)
vertical=np.concatenate((Array1,Array2),axis=1)
print(vertical)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [55]:
def display_products():
    print("Welcome to the online store!")
    print("Available products:")
    print("1. AI Response Simulator")
    print("2. Investment Decision")
    print("q. Exit")

def main():
    shopping_cart = []
    while True:
        display_products()
        choice = input("Enter the number corresponding to the product you want to add to the cart (or 'q' to quit): ")

        if choice.lower() == 'q':
            break
        choice=int(choice)
        if(choice==1):
          shopping_cart.append("AI Response Simulator ")
          print("AI Response Simulator added to the shopping cart!")
        elif(choice==2):
          shopping_cart.append("Investment Decision")
          print("Investment Decision added to the shopping cart")


    print("\nThank you for shopping with us! Goodbye.")


if __name__ == "__main__":
    main()

Welcome to the online store!
Available products:
1. AI Response Simulator
2. Investment Decision
q. Exit
Enter the number corresponding to the product you want to add to the cart (or 'q' to quit): 1
AI Response Simulator added to the shopping cart!
Welcome to the online store!
Available products:
1. AI Response Simulator
2. Investment Decision
q. Exit
Enter the number corresponding to the product you want to add to the cart (or 'q' to quit): 2
Investment Decision added to the shopping cart
Welcome to the online store!
Available products:
1. AI Response Simulator
2. Investment Decision
q. Exit
Enter the number corresponding to the product you want to add to the cart (or 'q' to quit): q

Thank you for shopping with us! Goodbye.


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [83]:
def check(email):
    importants = []
    promotions = []
    spams = []
    if 'Important' in email[0]:
        importants.append(email)
    elif 'Promotion' in email[0]:
        promotions.append(email)
    elif 'Spam' in email[0]:
        spams.append(email)
    return importants, promotions, spams

emails = [["This is Important Email"], ["This is Promotion Email"], ["This is Spam Email"]]
all_importants = []
all_promotions = []
all_spams = []
for email in emails:
    importants, promotions, spams = check(email)
    all_importants.extend(importants)
    all_promotions.extend(promotions)
    all_spams.extend(spams)

print("Important Email:", all_importants)
print("Promotions Email:", all_promotions)
print("Spams Email:", all_spams)


Important Email: [['This is Important Email']]
Promotions Email: [['This is Promotion Email']]
Spams Email: [['This is Spam Email']]


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [84]:
#code here
english_spanish_dict = {
    "hello": "hola",
    "world": "mundo",
    "cat": "gato",
    "dog": "perro",
}

def translate_word(word):
    return english_spanish_dict.get(word.lower(), "Translation not available")
while True:
    word = input("Enter an English word (or 'exit' to quit): ")
    if word.lower() == "exit":
        print("Good Bye!")
        break
    translation = translate_word(word)

    print(f"The Spanish translation of '{word}' is '{translation}'.")


Enter an English word (or 'exit' to quit): hello
The Spanish translation of 'hello' is 'hola'.
Enter an English word (or 'exit' to quit): exit
Good Bye!


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [93]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv",index_col="Rank")
df

Name Platform    Year  \
Rank                                                                       
1                                            Wii Sports      Wii  2006.0   
2                                     Super Mario Bros.      NES  1985.0   
3                                        Mario Kart Wii      Wii  2008.0   
4                                     Wii Sports Resort      Wii  2009.0   
5                              Pokemon Red/Pokemon Blue       GB  1996.0   
...                                                 ...      ...     ...   
16596                Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                     Men in Black II: Alien Escape       GC  2003.0   
16598  SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                        Know How 2       DS  2010.0   
16600                                  Spirits & Spells      GBA  2003.0   

              Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
Rank                                                                         
1            Sports    Nintendo     41.49     29.02      3.77         8.46   
2          Platform    Nintendo     29.08      3.58      6.81         0.77   
3            Racing    Nintendo     15.85     12.88      3.79         3.31   
4            Sports    Nintendo     15.75     11.01      3.28         2.96   
5      Role-Playing    Nintendo     11.27      8.89     10.22         1.00   
...             ...         ...       ...       ...       ...          ...   
16596      Platform       Kemco      0.01      0.00      0.00         0.00   
16597       Shooter  Infogrames      0.01      0.00      0.00         0.00   
16598        Racing  Activision      0.00      0.00      0.00         0.00   
16599        Puzzle    7G//AMES      0.00      0.01      0.00         0.00   
16600      Platform     Wanadoo      0.01      0.00      0.00         0.00   

       Global_Sales  
Rank                 
1             82.74  
2             40.24  
3             35.82  
4             33.00  
5             31.37  
...             ...  
16596          0.01  
16597          0.01  
16598          0.01  
16599          0.01  
16600          0.01  

[16598 rows x 10 columns]

In [98]:
#Calculate the total global sales for all games in the dataset.
total=df['Global_Sales'].sum()
print("Total Global Sales:",total)

Total Global Sales: 8920.44


In [115]:
#Find the game with the highest global sales.
highest = df.sort_values(by="Global_Sales", ascending=False).head(1)
print(highest.values[0])


['Wii Sports' 'Wii' 2006.0 'Sports' 'Nintendo' 41.49 29.02 3.77 8.46 82.74]


In [120]:
average=df[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']].mean()
print("Average:",average)

Average: NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [121]:
top_5=df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
top_5

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

In [125]:
total_sales=df.groupby('Genre')[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']].sum()
total_sales

NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36

In [128]:
popular=total_sales['NA_Sales'].idxmax()
popular

'Action'

In [129]:
last=df.tail(10)
last

Name Platform    Year  \
Rank                                                                        
16591                                   Mega Brain Boost       DS  2008.0   
16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV  2016.0   
16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP  2007.0   
16594                                Myst IV: Revelation       PC  2004.0   
16595                                           Plushees       DS  2008.0   
16596                 Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                      Men in Black II: Alien Escape       GC  2003.0   
16598   SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                         Know How 2       DS  2010.0   
16600                                   Spirits & Spells      GBA  2003.0   

              Genre              Publisher  NA_Sales  EU_Sales  JP_Sales  \
Rank                                                                       
16591        Puzzle  Majesco Entertainment      0.01      0.00      0.00   
16592        Action        dramatic create      0.00      0.00      0.01   
16593  Role-Playing     Falcom Corporation      0.00      0.00      0.01   
16594     Adventure                Ubisoft      0.01      0.00      0.00   
16595    Simulation              Destineer      0.01      0.00      0.00   
16596      Platform                  Kemco      0.01      0.00      0.00   
16597       Shooter             Infogrames      0.01      0.00      0.00   
16598        Racing             Activision      0.00      0.00      0.00   
16599        Puzzle               7G//AMES      0.00      0.01      0.00   
16600      Platform                Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
Rank                              
16591          0.0          0.01  
16592          0.0          0.01  
16593          0.0          0.01  
16594          0.0          0.01  
16595          0.0          0.01  
16596          0.0          0.01  
16597          0.0          0.01  
16598          0.0          0.01  
16599          0.0          0.01  
16600          0.0          0.01

In [130]:
top_3=df.groupby("Platform")["Global_Sales"].sum().nlargest(3)
top_3

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

In [132]:
market=(df.groupby("Genre")['Global_Sales'].sum()/100)
market

Genre
Action          17.5118
Adventure        2.3904
Fighting         4.4891
Misc             8.0996
Platform         8.3137
Puzzle           2.4495
Racing           7.3204
Role-Playing     9.2737
Shooter         10.3737
Simulation       3.9220
Sports          13.3093
Strategy         1.7512
Name: Global_Sales, dtype: float64

In [133]:

correlation_coefficient = df['NA_Sales'].corr(df['EU_Sales'])
print("Correlation coefficient between NA_Sales and EU_Sales:", correlation_coefficient)

Correlation coefficient between NA_Sales and EU_Sales: 0.7677267483702631
